language: ruby
rvm:
- 2.3.1
bundler_args: "--without production"
addons:
  code_climate:
    repo_token:
      secure: XJbqjJwiSf/Kn/8YH48VKxazcP7PRGxHRED7C2+iyyXJYygt1QL9MFbC4qUPrZg4dbyNt2IVRssi5HRgu+1y9jD9lzYTk2bX9KkGu4AIKYUXdg5gSYfvo05LOjGeDllqPyCqqv/h7PVV2BTZ1a0vxcaRa7UX4U0GdVXl11Sp5cgFgXjiJnpwSzMnet81INZu6VC063A40UTm+1Any5XGaik4pym6xECZeX/CknGfq61fjD8Vf7HSBx7g8Ujh/WWfTGND9bkgpYLqQ2wK6w6QkeekhkMdpdvy4bccemv6iSOTilfiE0qup60ZIhrbTFbk00ic1qQsEI3EkTDQuntSYvd+ScEksZcNeHEijRJHl6GvIYwn07EG9qeBwUizITC54ojbRHSBvZxU/GprSmQ9KYGJoWjR9r7SwLKlIipIi6ixMqYAiae0Gh1/m1Bve3RF37jUJTWI5h5pKUyPKGz+/4dTOxsbgzkzpSWmdUjmkRaQR/4ar6JRIZgIrElEeOPyiW0t3Vt3HHnSpdA8WzY1cSIs5FwPDI+5xGuIRWW2TrzDplTuScOlxjP6f8AM8qrFjjXl9h1WUzZNxArNl4cBUFADfz3HimDAGLwdyciBtj0HRrVCCJZYBXTp4J1+hDqW6knaEvLfygqQogzQIBu5uY1cBA4q6r55KlaTiWNaZSQ=